spring:
  application:
    name: pixgateway-backend
  security:
    user:
      name: admin
      password: admin123
  
  datasource:
    # Se existir DATABASE_URL na nuvem, ele usa. Se não, usa o seu localhost!
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/pixgateway_db}
    username: ${PGUSER:felipe}
    password: ${PGPASSWORD:pixpass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true